server:
  port: 9090
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:postgresql://localhost:5432/statsdb
    username: stats
    password: stats
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always